
import type { UserProfileData } from './types';

export const mockProfile: UserProfileData = {
  id: 'user-1',
  username: 'theclassylife',
  email: 'classy@example.com',
  avatarUrl: '/avatars/avatar-1.png',
  avatarHint: 'logo CL',
  stats: {
    posts: 2,
    followers: '1.2M',
    following: 150,
    topCountries: [
      { name: 'United States', percentage: 35.8 },
      { name: 'Brazil', percentage: 8.2 },
      { name: 'India', percentage: 6.9 },
      { name: 'United Kingdom', percentage: 3.1 },
      { name: 'Germany', percentage: 2.5 },
    ],
    topCities: [
        { name: 'New York', percentage: 2.1 },
        { name: 'London', percentage: 1.8 },
        { name: 'Sao Paulo', percentage: 1.5 },
        { name: 'Los Angeles', percentage: 1.2 },
    ],
    topAgeRanges: [
        { name: '18-24', percentage: 30 },
        { name: '25-34', percentage: 45 },
        { name: '35-44', percentage: 15 },
        { name: '45-54', percentage: 7 },
        { name: '55+', percentage: 3 },
    ],
    genderBreakdown: [
        { name: 'Women', percentage: 65 },
        { name: 'Men', percentage: 35 },
    ],
    profileActivity: {
        total: 18739,
        change: -12.5,
        vsDate: 'vs 9 Aug - 8 Sep',
        visits: { total: 18739, change: -12.5 },
        linkTaps: { total: 0, changeText: '' },
    },
    viewsBreakdown: [
        { name: 'followers', value: 70, color: 'hsl(var(--chart-1))' },
        { name: 'non-followers', value: 30, color: 'hsl(var(--chart-2))' },
    ],
    totalViews: 14700,
    accountsReached: { value: 11800000, change: -12.5 },
    dateRangeText: '9 Sep - 8 Oct',
  },
  name: 'CLASSY LIFE ™',
  bio: [
    '🔥Motivated by @johnmalek',
    '🎥Daily clips & insights',
    'Insta: @johnmalek'
  ],
  link: 'theclassylife.com',
  professionalDashboard: {
    views: '11.8M',
  },
  posts: [
    {
      id: 'post-1',
      imageUrl: 'https://picsum.photos/seed/post1/600/1000',
      imageHint: 'couple luxury',
      views: 14000,
      likes: 975,
      comments: 5,
      shares: 23,
      saves: 112,
      caption: 'Rich Billionaire Family Lifestyle in Monaco 🇲🇨',
      type: 'reel',
      watchTime: '2h 45m 12s',
      interactions: 1115,
      reposts: 0,
      profileActivity: 52,
      follows: 12,
      viewsBreakdown: { instagram: 14000, facebook: 2300 },
      timeseries: [
        { date: '2023-09-01', views: 500 },
        { date: '2023-09-02', views: 750 },
        { date: '2023-09-03', views: 1200 },
        { date: '2023-09-04', views: 900 },
        { date: '2023-09-05', views: 1500 },
        { date: '2023-09-06', views: 1800 },
        { date: '2023-09-07', views: 2200 },
      ],
      audienceBreakdown: { followers: 60, nonFollowers: 40 },
      genderBreakdown: { men: 35, women: 65 },
      ageBreakdown: [
        { range: '18-24', percentage: 16.7 },
        { range: '25-34', percentage: 79.2 },
        { range: '35-44', percentage: 4.2 },
      ],
      countryBreakdown: [
        { name: 'United States', percentage: 40 },
        { name: 'Brazil', percentage: 25 },
        { name: 'France', percentage: 15 },
        { name: 'Japan', percentage: 10 },
        { name: 'Canada', percentage: 10 },
      ],
      topCities: [
        { name: 'New York', percentage: 2.1 },
        { name: 'London', percentage: 1.8 },
        { name: 'Sao Paulo', percentage: 1.5 },
        { name: 'Los Angeles', percentage: 1.2 },
      ],
      viewSources: [
        { source: 'Your profile', percentage: 45.2 },
        { source: 'Reels tab', percentage: 30.1 },
        { source: 'Explore', percentage: 15.7 },
        { source: 'Hashtag pages', percentage: 5.5 },
        { source: 'Other', percentage: 3.5 },
      ],
      accountsReached: 12300,
      retentionData: [
        { timestamp: 0, retention: 100 },
        { timestamp: 3, retention: 95 },
        { timestamp: 6, retention: 80 },
        { timestamp: 9, retention: 75 },
        { timestamp: 12, retention: 60 },
        { timestamp: 15, retention: 50 },
        { timestamp: 18, retention: 40 },
        { timestamp: 21, retention: 30 },
        { timestamp: 25, retention: 20 },
        { timestamp: 30, retention: 10 },
      ],
      likesOverTime: [
        { timestamp: 0, retention: 18 },
        { timestamp: 4, retention: 18 },
        { timestamp: 8, retention: 12 },
        { timestamp: 12, retention: 12 },
        { timestamp: 16, retention: 8 },
        { timestamp: 20, retention: 8 },
        { timestamp: 24, retention: 8 },
        { timestamp: 28, retention: 5 },
        { timestamp: 32, retention: 5 },
        { timestamp: 36, retention: 5 },
        { timestamp: 40, retention: 2 },
        { timestamp: 44, retention: 2 },
      ],
      skipRate: 25,
      typicalSkipRate: '30-40%',
      avgWatchTime: 18,
      viewRate: 63.3,
      interactionsBreakdown: { followers: 70, nonFollowers: 30 },
      accountsEngaged: 1100,
    },
    {
      id: 'post-day-in-life',
      imageUrl: 'https://picsum.photos/seed/dayinlife/600/1000',
      imageHint: 'street style',
      views: 10000,
      likes: 800,
      comments: 12,
      shares: 15,
      saves: 90,
      caption: 'A day in the life',
      type: 'reel',
      accountsReached: 9500,
      viewSources: [
        { source: 'Your profile', percentage: 55.2 },
        { source: 'Reels tab', percentage: 20.1 },
        { source: 'Explore', percentage: 15.7 },
        { source: 'Hashtag pages', percentage: 5.5 },
        { source: 'Other', percentage: 3.5 },
      ],
    },
  ],
};
