// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "apiKey": "AIzaSyAcptqbjsGseoq4TtHHvqZ1DlSwjm0Xk0U",
  "authDomain": "nikuinsdight.firebaseapp.com",
  "projectId": "nikuinsdight",
  "storageBucket": "nikuinsdight.firebasestorage.app",
  "messagingSenderId": "179121052262",
  "appId": "1:179121052262:web:d837a41f3028e6e1536ba7"
};
